import "./globals.css";
import { en, kr } from "./fonts";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${en.className}, ${kr.className}`}>
            <body>{children}</body>
        </html>
    );
}
